import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import GitHubCorner from "./GitHubCorner";
import Providers from "./Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rock Paper Scissors",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ position: 'relative', minHeight: '100vh' }}>
        <div className="flex flex-col items-center" style={{ padding: '20px' }}>
          <Providers>
            <main>{children}</main>
          </Providers>
        </div>
        <GitHubCorner />
      </body>
    </html>
  );
}
